CREATE TABLE IF NOT EXISTS accounts (
    account_id  VARCHAR(255)   NOT NULL,
    balance     NUMERIC(19, 4) NOT NULL,
    version     BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS transfers (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    from_account VARCHAR(255)   NOT NULL,
    to_account   VARCHAR(255)   NOT NULL,
    amount       NUMERIC(19, 4) NOT NULL,
    date         TIMESTAMP      NOT NULL,
    CONSTRAINT pk_transfers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS idempotency_records (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key  VARCHAR(255) NOT NULL,
    request_hash     VARCHAR(64)  NOT NULL,
    transfer_id      BIGINT       NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    CONSTRAINT pk_idempotency_records PRIMARY KEY (id),
    CONSTRAINT uq_idempotency_key UNIQUE (idempotency_key)
);